language: python

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    -
    - LANG=
    - PYTHONIOENCODING=ascii
    - PYTHONIOENCODING=utf-8
    - PYTHONOPTIMIZE=x

before_script:
    # This is needed for Python multiprocessing.
    # https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install:
    - pip install --quiet git+https://github.com/google/yapf
    - python setup.py --quiet install

script:
    - python test_pyformat.py
    - pyformat pyformat.py
    - python test_acid.py setup.py

after_success:
    - pip install --quiet coverage
    - make coverage

    - pip install --quiet coveralls
    - coveralls
